networks:
  app_network:
    name: app_network
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: bankly_mysql_service
    restart: always
    networks:
      - app_network
    ports:
      - $DB_PORT:3306
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_HOST=%
    command: ['--default-authentication-plugin=mysql_native_password']
  account-api:
    image: baldini/testacesso
    container_name: bankly_api
    restart: always
    ports:
      - $BANKLY_SERVICE_PORT:80
