networks:
  app_network:
    name: app_network
    driver: bridge

services:
  bankly-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: bankly_app
    ports:
      - $SERVER_PORT:3000
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app_network
    env_file:
      - .env
    restart: always
  mysql:
    image: mysql:8.0
    container_name: bankly_mysql_service
    restart: always
    networks:
      - app_network
    ports:
      - $DB_PORT:3306
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_HOST=%
    command: ['--authentication-policy=mysql_native_password']
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: bankly_rabbitmq_service
    restart: always
    networks:
      - app_network
    ports:
      - $RABBITMQ_AMQP_PORT:5672
      - $RABBITMQ_HTTP_PORT:15672
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USERNAME
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
